load 'tasks/setup.rb'


ensure_in_path 'lib'
require 'ping_cache'

task :default => 'spec:run'

PROJ.name = 'ping_cache'
PROJ.authors = 'Tyler Montgomery'
PROJ.email = 'tyler.a.montgomery@gmail.com'
PROJ.url = 'http://pingcache.heroku.com'
PROJ.version = "0.1.0"
PROJ.rubyforge.name = 'ping_cache'
PROJ.summary = "passive location awareness"
PROJ.description = "passive location awareness"
PROJ.spec.opts << '--color'

# EOF